services:
  pentest:
    build:
      context: .
      target: production
    image: pentest
    container_name: pentest
    environment:
      APPINSIGHTS_CLOUDROLE: pentest-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
